import dayjs from 'dayjs/esm';
import { IUser } from 'app/entities/user/user.model';
import { IDiploma } from 'app/entities/diploma/diploma.model';
import { ILanguage } from 'app/entities/language/language.model';
import { ISite } from 'app/entities/site/site.model';
import { ICountry } from 'app/entities/country/country.model';
import { INationality } from 'app/entities/nationality/nationality.model';
import { IJob } from 'app/entities/job/job.model';
import { IDepartement } from 'app/entities/departement/departement.model';
import { IGroup } from 'app/entities/group/group.model';
import { ICourse } from 'app/entities/course/course.model';
import { ISession } from 'app/entities/session/session.model';
import { Role } from 'app/entities/enumerations/role.model';
import { AccountStatus } from 'app/entities/enumerations/account-status.model';
import { Sex } from 'app/entities/enumerations/sex.model';

export interface IUserCustom {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  code?: string | null;
  accountName?: string | null;
  role?: keyof typeof Role | null;
  accountStatus?: keyof typeof AccountStatus | null;
  phoneNumber1?: string | null;
  phoneNumver2?: string | null;
  sex?: keyof typeof Sex | null;
  birthdate?: dayjs.Dayjs | null;
  photo?: string | null;
  photoContentType?: string | null;
  address?: string | null;
  facebook?: string | null;
  telegramUserCustomId?: string | null;
  telegramUserCustomName?: string | null;
  biography?: string | null;
  bankAccountDetails?: string | null;
  user?: Pick<IUser, 'id' | 'login'> | null;
  diplomas?: Pick<IDiploma, 'id' | 'title'>[] | null;
  languages?: Pick<ILanguage, 'id' | 'nameAr'>[] | null;
  site13?: Pick<ISite, 'id' | 'nameAr'> | null;
  country?: Pick<ICountry, 'id' | 'nameAr'> | null;
  nationality?: Pick<INationality, 'id' | 'nameAr'> | null;
  job?: Pick<IJob, 'id' | 'titleAr'> | null;
  departement2?: Pick<IDepartement, 'id' | 'nameAr'> | null;
  groups?: Pick<IGroup, 'id' | 'nameAr'>[] | null;
  courses?: Pick<ICourse, 'id' | 'titleAr'>[] | null;
  sessions2s?: Pick<ISession, 'id' | 'title'>[] | null;
  sessions3s?: Pick<ISession, 'id' | 'title'>[] | null;
}

export type NewUserCustom = Omit<IUserCustom, 'id'> & { id: null };
