import dayjs from 'dayjs/esm';
import { IUser } from 'app/entities/user/user.model';
import { ICertificate } from 'app/entities/certificate/certificate.model';
import { IAnswer } from 'app/entities/answer/answer.model';
import { IQuizResult } from 'app/entities/quiz-result/quiz-result.model';
import { IReview } from 'app/entities/review/review.model';
import { IEnrolement } from 'app/entities/enrolement/enrolement.model';
import { IProgression } from 'app/entities/progression/progression.model';
import { ITickets } from 'app/entities/tickets/tickets.model';
import { ISponsoring } from 'app/entities/sponsoring/sponsoring.model';
import { IDepense } from 'app/entities/depense/depense.model';
import { IDiploma } from 'app/entities/diploma/diploma.model';
import { ILanguage } from 'app/entities/language/language.model';
import { ISite } from 'app/entities/site/site.model';
import { ICountry } from 'app/entities/country/country.model';
import { INationality } from 'app/entities/nationality/nationality.model';
import { IJob } from 'app/entities/job/job.model';
import { IDepartement } from 'app/entities/departement/departement.model';
import { IGroup } from 'app/entities/group/group.model';
import { ICourse } from 'app/entities/course/course.model';
import { ISession } from 'app/entities/session/session.model';
import { Role } from 'app/entities/enumerations/role.model';
import { AccountStatus } from 'app/entities/enumerations/account-status.model';
import { Sex } from 'app/entities/enumerations/sex.model';

export interface IUserCustom {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  code?: string | null;
  accountName?: string | null;
  role?: keyof typeof Role | null;
  accountStatus?: keyof typeof AccountStatus | null;
  phoneNumber1?: string | null;
  phoneNumver2?: string | null;
  sex?: keyof typeof Sex | null;
  birthdate?: dayjs.Dayjs | null;
  photo?: string | null;
  photoContentType?: string | null;
  address?: string | null;
  facebook?: string | null;
  telegramUserCustomId?: string | null;
  telegramUserCustomName?: string | null;
  biography?: string | null;
  bankAccountDetails?: string | null;
  user?: Pick<IUser, 'id' | 'login'> | null;
  certificates?: ICertificate[] | null;
  answers?: IAnswer[] | null;
  quizResults?: IQuizResult[] | null;
  reviews?: IReview[] | null;
  enrolements?: IEnrolement[] | null;
  progressions?: IProgression[] | null;
  tickets?: ITickets[] | null;
  sponsorings?: ISponsoring[] | null;
  depenses?: IDepense[] | null;
  diplomas?: IDiploma[] | null;
  languages?: ILanguage[] | null;
  site13?: ISite | null;
  country?: ICountry | null;
  nationality?: INationality | null;
  job?: IJob | null;
  departement2?: IDepartement | null;
  groups?: IGroup[] | null;
  courses?: ICourse[] | null;
  sessions2s?: ISession[] | null;
  sessions3s?: ISession[] | null;
}

export type NewUserCustom = Omit<IUserCustom, 'id'> & { id: null };
